module.exports = {
  "info":
      "It is evil. Friendship is temporary!",
  "colors":[
    "red",
    "green",
    "blue",
    "yellow",
    "pink",
    "lime",
    "cyan",
    "white",
    "black",
    "brown"
  ],
  "cards":{
    "0":{
      "type":"number",
      draw:0,
      color:"random"
    },
    "1":{
      type:"number",
      draw:0,
      color:"random"
    },
    "2":{
      type:"number",
      draw:0,
      color:"random"
    },
    "3":{
      type:"number",
      draw:0,
      color:"random"
    },
    "4":{
      type:"number",
      draw:0,
      color:"random"
    },
    "5":{
      type:"number",
      draw:0,
      color:"random"
    },
    "6":{
      type:"number",
      draw:0,
      color:"random"
    },
    "7":{
      type:"number",
      draw:0,
      color:"random"
    },
    "8":{
      type:"number",
      draw:0,
      color:"random"
    },
    "9":{
      type:"number",
      draw:0,
      color:"random"
    },
    "A":{
      type:"number",
      draw:0,
      color:"random"
    },
    "B":{
      type:"number",
      draw:0,
      color:"random"
    },
    "C":{
      type:"number",
      draw:0,
      color:"random"
    },
    "D":{
      type:"number",
      draw:0,
      color:"random"
    },
    "E":{
      type:"number",
      draw:0,
      color:"random"
    },
    "F":{
      type:"number",
      draw:0,
      color:"random"
    },
    "draw-two":{
      type:"number",
      draw:2,
      color:"random"
    },
    "draw-four":{
      type:"number",
      draw:4,
      color:"random"
    },
    "color-pick":{
      type:"color",
      draw:0,
      color:"wild"
    },
    "draw-four":{
      type:"color",
      draw:4,
      color:"wild"
    },
    "draw-eight":{
      type:"color",
      draw:8,
      color:"wild"
    },
    "reverse":{
      type:"reverse",
      draw:0,
      color:"random"
    },
    "skip":{
      type:"skip",
      draw:0,
      color:"random"
    }
  }
}